<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC4155" name="Test" tests="5" failures="2" timestamp="20 Apr 2017 07:08:09 GMT" time="62.941" errors="0">
  <testcase name="loginTest" time="0.732" classname="com.saf.so.smartoffice.Starter"/>
  <testcase name="AddBuildingTest" time="40.322" classname="com.saf.so.smartoffice.Starter"/>
  <testcase name="AddFlrTest" time="21.826" classname="com.saf.so.smartoffice.Starter"/>
  <testcase name="loginTest" time="0.002" classname="com.saf.so.smartoffice.Starter3">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.saf.so.smartoffice.Starter3.loginTest(Starter3.java:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="addusermembertest" time="0.002" classname="com.saf.so.smartoffice.Starter3">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.saf.so.smartoffice.Starter3.addusermembertest(Starter3.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- addusermembertest -->
</testsuite> <!-- Test -->
